### ISSUE TITLE
vmur lock scope is too wide; vmur can't wait for a lock to be available; vmur doesn't support tag info for rscs or printers etc.

### ISSUE THREAD

**Issue by donald-russell** [ibm-s390-tools/s390-tools#15] opened 2017-11-07 02:44 UTC
I have a solution for these problems, but am new to github, Please bear with me as I figuure out how this all works.

Next challenge: How to get myself assigned to this issue?

**Comment by michael-holzheu** [comment] 2017-11-07 16:10
@donald-russell : You already address all these issues in PR #14, right? So could you please first rework your patch series in PR #14 so that we can get an overview on what exactly your suggestions are?

> Next challenge: How to get myself assigned to this issue?

If the issue is valid, it will be assigned to our vmur maintainer.

**Comment by michael-holzheu** [comment] 2017-11-09 20:56
Closing this one and keep on discussing in PR #14.

**Closed by michael-holzheu** 2017-11-09 20:56 UTC
